# Generated by Django 4.2 on 2024-11-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbFactura',
            fields=[
                ('idfactura', models.AutoField(db_column='IdFactura', primary_key=True, serialize=False)),
                ('costototal', models.DecimalField(db_column='CostoTotal', decimal_places=0, max_digits=18)),
                ('descuentoaplicado', models.BooleanField(db_column='DescuentoAplicado')),
                ('totaldescuentoaplicado', models.DecimalField(blank=True, db_column='TotalDescuentoAplicado', decimal_places=0, max_digits=18, null=True)),
                ('cantidadcuotas', models.IntegerField(blank=True, db_column='CantidadCuotas', null=True)),
                ('cuotaspagadas', models.IntegerField(blank=True, db_column='CuotasPagadas', null=True)),
                ('costoporcuota', models.DecimalField(blank=True, db_column='CostoPorCuota', decimal_places=0, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'Tb_Factura',
                'managed': False,
            },
        ),
    ]
