# Generated by Django 4.2 on 2024-11-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbModalidaddepago',
            fields=[
                ('idmodalidaddepago', models.AutoField(db_column='IdModalidadDePago', primary_key=True, serialize=False)),
                ('nombremodalidad', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='NombreModalidad', max_length=50)),
            ],
            options={
                'db_table': 'Tb_ModalidadDePago',
                'managed': False,
            },
        ),
    ]
