# Generated by Django 4.2 on 2024-11-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbHistorialclinico',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('motivo', models.TextField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Motivo', null=True)),
                ('historiadeldolor', models.TextField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='HistoriaDelDolor', null=True)),
                ('interpretacionradiografica', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='InterpretacionRadiografica', max_length=100, null=True)),
                ('observacion', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Observacion', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Tb_HistorialClinico',
                'managed': False,
            },
        ),
    ]
