# Generated by Django 4.2 on 2024-11-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbMontodedescuento',
            fields=[
                ('idmontodedescuento', models.AutoField(db_column='IdMontoDeDescuento', primary_key=True, serialize=False)),
                ('porcentajedescuento', models.DecimalField(db_column='PorcentajeDescuento', decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'Tb_MontoDeDescuento',
                'managed': False,
            },
        ),
    ]
