# Generated by Django 4.2 on 2024-11-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbPaciente',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('nombrecompleto', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='NombreCompleto', max_length=60)),
                ('cedula', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Cedula', max_length=16, null=True)),
                ('edad', models.IntegerField(db_column='Edad')),
                ('direccion', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Direccion', max_length=100, null=True)),
                ('telefono', models.IntegerField(blank=True, db_column='Telefono', null=True)),
                ('ocupacion', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Ocupacion', max_length=20, null=True)),
                ('antecedentes', models.TextField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Antecedentes', null=True)),
                ('isdeleted', models.BooleanField(blank=True, db_column='IsDeleted', null=True)),
            ],
            options={
                'db_table': 'Tb_Paciente',
                'managed': False,
            },
        ),
    ]
